### PR TITLE
feat: Add some hover effects in the navbar #6

### LINKED ISSUE #6: Add some hover effects in the navbar
Add scaling effect on hovering the in the navbar @avibiradar100 I can fix that. Please assign it to me.
Screenshot (165)

### PR DESCRIPTION
**Pull request by harshsbhandari**
Fixes Issue
My PR closes https://github.com/avibiradar100/SaahityaWce/issues/6

👨‍💻 Changes proposed(What did you do ?)
Added color on hovering the navbar

✔️ Check List (Check all the applicable boxes)
 My code follows the code style of this project.
 This PR does not contain plagiarised content.
 The title and description of the PR is clear and explains the approach.

📷 Screenshots
Screenshot (169)

### CODE REVIEW

**Comment by avibiradar100** [comment]
please make PR in this format https://github.com/avibiradar100/SaahityaWce/pull/5

**Comment by avibiradar100** [comment]
it is a feature  so make it 
feat: < your PR Name> and instead of  fixes make it closes

**Comment by harshsbhandari** [comment]
> it is a feature so make it feat: < your PR Name> and instead of fixes make it closes

@avibiradar100  DONE

**Comment by avibiradar100** [comment]
Thanks @harshsbhandari  for contributing..🥳🎉

**Pull request merged**
